# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "zigimg-0.1.0-8_eo2sPVFwAm8y-DVfaCHNKQIpv9oHl_mbcKbGQZRLrK";
    path = fetchzip {
      url = "https://codeload.github.com/zigimg/zigimg/tar.gz/refs/heads/master";
      hash = "sha256-2PoVXThvGLJ3OZc4bJ15pIDGLwjS5wLitnYp32d6yps=";
    };
  }
]
